# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: OpenEyes
email: openeyes@apperta.org
description: > # this means to ignore newlines until "baseurl:"
  OpenEyes™ is an Electronic Medical Record (EMR) application for ophthalmology, which enables clinicians to access all of the information they need about their patients in one place.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://openeyes.apperta.org" # the base hostname & protocol for your site
twitter_username: openeyes_oef
github_username:  openeyes

collections:
  - subcommittees
  - directors
  - members
  - products
  - oeusers
  - posts

# Build settings
markdown: kramdown
exclude: ["README.md"]
include: ['_pages']

